'use client';

// ============================================================
// Roblox Asset AI - Inspector & Iteration History (Right Sidebar)
// ============================================================

import React, { useState } from 'react';
import {
  Download,
  AlertCircle,
  CheckCircle2,
  TrendingUp,
  History,
  FileCode,
  Layers,
  Wand2,
  Copy,
  Check,
  ChevronRight,
  ChevronDown,
  Terminal,
  Code2,
  Box,
  Sparkles,
} from 'lucide-react';
import {
  IterationRecord,
  RobloxModelIR,
  RobloxAnimationIR,
  RobloxPartIR,
} from '@/lib/types/roblox';

// Helper: Convert RobloxModelIR to executable Roblox Studio Luau script
function generateRobloxLuaScript(model: RobloxModelIR): string {
  const lines: string[] = [
    `-- ========================================================`,
    `-- Generated by Roblox Asset AI: ${model.name}`,
    `-- Paste into Roblox Studio Command Bar (View > Command Bar)`,
    `-- ========================================================`,
    `local model = Instance.new("Model")`,
    `model.Name = ${JSON.stringify(model.name)}`,
    ``,
    `local parts = {}`,
  ];

  model.instances.forEach((inst, index) => {
    const part = inst as RobloxPartIR;
    const varName = `p${index + 1}`;
    lines.push(`-- [${index + 1}] ${part.name}`);
    lines.push(`local ${varName} = Instance.new(${JSON.stringify(part.className)})`);
    lines.push(`${varName}.Name = ${JSON.stringify(part.name)}`);
    if (part.size) {
      lines.push(`${varName}.Size = Vector3.new(${part.size[0]}, ${part.size[1]}, ${part.size[2]})`);
    }
    if (part.position) {
      lines.push(`${varName}.Position = Vector3.new(${part.position[0]}, ${part.position[1]}, ${part.position[2]})`);
    }
    if (part.rotation && (part.rotation[0] !== 0 || part.rotation[1] !== 0 || part.rotation[2] !== 0)) {
      lines.push(`${varName}.Orientation = Vector3.new(${part.rotation[0]}, ${part.rotation[1]}, ${part.rotation[2]})`);
    }
    if (part.shape && part.className === 'Part') {
      lines.push(`${varName}.Shape = Enum.PartType.${part.shape}`);
    }
    if (part.material) {
      lines.push(`${varName}.Material = Enum.Material.${part.material}`);
    }
    if (part.color) {
      lines.push(`${varName}.Color = Color3.fromRGB(${part.color[0]}, ${part.color[1]}, ${part.color[2]})`);
    }
    if (part.transparency !== undefined && part.transparency > 0) {
      lines.push(`${varName}.Transparency = ${part.transparency}`);
    }
    if (part.reflectance !== undefined && part.reflectance > 0) {
      lines.push(`${varName}.Reflectance = ${part.reflectance}`);
    }
    if ('anchored' in part) {
      lines.push(`${varName}.Anchored = ${part.anchored !== false ? 'true' : 'false'}`);
    }
    if ('canCollide' in part) {
      lines.push(`${varName}.CanCollide = ${part.canCollide !== false ? 'true' : 'false'}`);
    }
    lines.push(`${varName}.Parent = model`);
    lines.push(`parts[${JSON.stringify(part.id)}] = ${varName}`);
    lines.push(``);
  });

  if (model.primaryPartId) {
    lines.push(`if parts[${JSON.stringify(model.primaryPartId)}] then`);
    lines.push(`    model.PrimaryPart = parts[${JSON.stringify(model.primaryPartId)}]`);
    lines.push(`end`);
    lines.push(``);
  }

  lines.push(`model.Parent = workspace`);
  lines.push(`print("[Roblox Asset AI] Successfully spawned '" .. model.Name .. "' into workspace!")`);

  return lines.join('\n');
}

// Helper: Convert RobloxAnimationIR to KeyframeSequence Luau script
function generateRobloxAnimationLuaScript(anim: RobloxAnimationIR): string {
  const lines: string[] = [
    `-- ========================================================`,
    `-- Generated by Roblox Asset AI: Animation '${anim.name}'`,
    `-- KeyframeSequence Generator for Roblox Studio`,
    `-- ========================================================`,
    `local kfs = Instance.new("KeyframeSequence")`,
    `kfs.Name = ${JSON.stringify(anim.name)}`,
    `kfs.Loop = ${anim.loop ? 'true' : 'false'}`,
    `kfs.Priority = Enum.AnimationPriority.${anim.priority || 'Action'}`,
    ``,
  ];

  anim.keyframes.forEach((kf, kfIdx) => {
    const kfVar = `kf_${kfIdx}`;
    lines.push(`local ${kfVar} = Instance.new("Keyframe")`);
    lines.push(`${kfVar}.Time = ${kf.time}`);
    lines.push(`${kfVar}.Parent = kfs`);

    kf.poses.forEach((pose, pIdx) => {
      const pVar = `pose_${kfIdx}_${pIdx}`;
      const pos = pose.position || [0, 0, 0];
      const rot = pose.rotation || [0, 0, 0];
      lines.push(`local ${pVar} = Instance.new("Pose")`);
      lines.push(`${pVar}.Name = ${JSON.stringify(pose.boneName)}`);
      lines.push(`${pVar}.CFrame = CFrame.new(${pos.join(', ')}) * CFrame.Angles(math.rad(${rot[0]}), math.rad(${rot[1]}), math.rad(${rot[2]}))`);
      lines.push(`${pVar}.EasingDirection = Enum.EasingDirection.${pose.easingDirection || 'Out'}`);
      lines.push(`${pVar}.EasingStyle = Enum.EasingStyle.${pose.easingStyle || 'Quad'}`);
      lines.push(`${pVar}.Parent = ${kfVar}`);
    });
    lines.push(``);
  });

  lines.push(`kfs.Parent = workspace`);
  lines.push(`print("[Roblox Asset AI] KeyframeSequence '" .. kfs.Name .. "' loaded (" .. #kfs:GetKeyframes() .. " keyframes)!")`);
  return lines.join('\n');
}

interface InspectorPanelProps {
  iterations: IterationRecord[];
  activeIterationIndex: number;
  onSelectIteration: (index: number) => void;
  onImproveFurther?: () => void;
  isGenerating: boolean;
  modelIR?: RobloxModelIR | null;
  animationIR?: RobloxAnimationIR | null;
}

export default function InspectorPanel({
  iterations,
  activeIterationIndex,
  onSelectIteration,
  onImproveFurther,
  isGenerating,
  modelIR,
  animationIR,
}: InspectorPanelProps) {
  const [activeTab, setActiveTab] = useState<'iterations' | 'scene_graph' | 'export'>('iterations');
  const [copiedJson, setCopiedJson] = useState(false);
  const [copiedLua, setCopiedLua] = useState(false);
  const [showLuaPreview, setShowLuaPreview] = useState(false);
  const [selectedPartId, setSelectedPartId] = useState<string | null>(null);
  const [downloadingFormat, setDownloadingFormat] = useState<string | null>(null);

  const activeRecord = iterations[activeIterationIndex] || iterations[iterations.length - 1];
  const critique = activeRecord?.critique;
  const qualityScore = critique ? Math.round(critique.qualityScore * 100) : 0;

  // Active target model or animation
  const currentModel = activeRecord?.modelIR || modelIR;
  const currentAnimation = activeRecord?.animationIR || animationIR;

  // Selected Part in scene graph
  const selectedPart = currentModel?.instances.find(
    (inst) => inst.id === selectedPartId
  ) as RobloxPartIR | undefined;

  // Handle Lua Script Copy
  const handleCopyLuaScript = () => {
    let script = '';
    if (currentModel) {
      script = generateRobloxLuaScript(currentModel);
    } else if (currentAnimation) {
      script = generateRobloxAnimationLuaScript(currentAnimation);
    }
    if (!script) return;

    navigator.clipboard.writeText(script);
    setCopiedLua(true);
    setTimeout(() => setCopiedLua(false), 2200);
  };

  // Handle Asset Download (.rbxmx / .rbxm / json)
  const handleDownload = async (format: 'rbxmx' | 'rbxm' | 'json') => {
    if (!modelIR && !animationIR) return;
    setDownloadingFormat(format);

    try {
      const res = await fetch('/api/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          modelIR: activeRecord?.modelIR || modelIR,
          animationIR: activeRecord?.animationIR || animationIR,
          format,
        }),
      });

      if (!res.ok) {
        const err = await res.json();
        alert(`Export failed: ${err.error || 'Validation error'}`);
        setDownloadingFormat(null);
        return;
      }

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const assetName = activeRecord?.modelIR?.name || activeRecord?.animationIR?.name || 'RobloxAsset';
      a.download = `${assetName}.${format}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: any) {
      alert(`Export error: ${err.message}`);
    } finally {
      setDownloadingFormat(null);
    }
  };

  const handleCopyJson = () => {
    const data = activeRecord?.modelIR || modelIR;
    if (!data) return;
    navigator.clipboard.writeText(JSON.stringify(data, null, 2));
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-studio-900 border-l border-studio-800 text-studio-100 overflow-hidden">
      {/* Top Tabs */}
      <div className="flex items-center border-b border-studio-800 bg-studio-950 px-2 pt-2 gap-1 text-xs">
        <button
          onClick={() => setActiveTab('iterations')}
          className={`flex items-center gap-1.5 px-3 py-2 border-b-2 font-medium transition ${
            activeTab === 'iterations'
              ? 'border-roblox-blue text-roblox-blue bg-studio-900/60 rounded-t'
              : 'border-transparent text-studio-400 hover:text-studio-200'
          }`}
        >
          <History className="w-3.5 h-3.5" />
          <span>Iterations ({iterations.length})</span>
        </button>
        <button
          onClick={() => setActiveTab('scene_graph')}
          className={`flex items-center gap-1.5 px-3 py-2 border-b-2 font-medium transition ${
            activeTab === 'scene_graph'
              ? 'border-roblox-blue text-roblox-blue bg-studio-900/60 rounded-t'
              : 'border-transparent text-studio-400 hover:text-studio-200'
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>Scene Tree</span>
        </button>
        <button
          onClick={() => setActiveTab('export')}
          className={`flex items-center gap-1.5 px-3 py-2 border-b-2 font-medium transition ${
            activeTab === 'export'
              ? 'border-roblox-blue text-roblox-blue bg-studio-900/60 rounded-t'
              : 'border-transparent text-studio-400 hover:text-studio-200'
          }`}
        >
          <Download className="w-3.5 h-3.5" />
          <span>Export</span>
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {/* Quality Score Meter */}
        <div className="bg-studio-950 p-3.5 rounded-xl border border-studio-800 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-medium text-studio-400 uppercase tracking-wider">
              Asset Quality Score
            </span>
            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-roblox-green">
              <TrendingUp className="w-3.5 h-3.5" />
              <span>{qualityScore}%</span>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="w-full h-2 bg-studio-850 rounded-full overflow-hidden">
            <div
              className={`h-full transition-all duration-500 rounded-full ${
                qualityScore >= 85
                  ? 'bg-roblox-green'
                  : qualityScore >= 70
                  ? 'bg-roblox-yellow'
                  : 'bg-roblox-red'
              }`}
              style={{ width: `${qualityScore}%` }}
            />
          </div>

          {/* Sub-metrics breakdown */}
          {critique?.metrics && (
            <div className="grid grid-cols-2 gap-2 pt-2 border-t border-studio-850 text-[11px]">
              <div className="flex justify-between text-studio-400">
                <span>Proportions:</span>
                <span className="font-mono text-studio-200">
                  {Math.round(critique.metrics.proportions * 100)}%
                </span>
              </div>
              <div className="flex justify-between text-studio-400">
                <span>Geometry:</span>
                <span className="font-mono text-studio-200">
                  {Math.round(critique.metrics.geometry * 100)}%
                </span>
              </div>
              <div className="flex justify-between text-studio-400">
                <span>Colors & Mats:</span>
                <span className="font-mono text-studio-200">
                  {Math.round(critique.metrics.colorMaterial * 100)}%
                </span>
              </div>
              <div className="flex justify-between text-studio-400">
                <span>Structure:</span>
                <span className="font-mono text-studio-200">
                  {Math.round(critique.metrics.structure * 100)}%
                </span>
              </div>
            </div>
          )}
        </div>

        {/* TAB 1: ITERATIONS & CRITIQUE HISTORY */}
        {activeTab === 'iterations' && (
          <div className="space-y-4">
            {/* Iteration Selector Pill Buttons */}
            {iterations.length > 0 && (
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-studio-400">
                  Self-Improvement Attempts
                </label>
                <div className="grid grid-cols-4 gap-1 p-1 bg-studio-950 rounded-lg border border-studio-800">
                  {iterations.map((iter, idx) => {
                    const isSelected = activeIterationIndex === idx;
                    const isLast = idx === iterations.length - 1;
                    return (
                      <button
                        key={idx}
                        onClick={() => onSelectIteration(idx)}
                        className={`py-1.5 px-2 rounded-md text-xs font-medium transition text-center ${
                          isSelected
                            ? 'bg-roblox-blue text-white shadow'
                            : 'text-studio-400 hover:text-studio-200 hover:bg-studio-850'
                        }`}
                      >
                        {isLast && iterations.length > 1 ? 'Final' : `Att. ${iter.iterationNumber}`}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Current Attempt Visual Snapshot & Summary */}
            {activeRecord && (
              <div className="bg-studio-950 p-3 rounded-xl border border-studio-800 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-studio-200">
                    Attempt {activeRecord.iterationNumber} Evaluation
                  </span>
                  <span className="text-[10px] font-mono text-studio-500">
                    {activeRecord.durationMs}ms
                  </span>
                </div>

                {/* Rendered Preview Thumbnail */}
                {activeRecord.renderPreviewDataUrl && (
                  <div className="rounded-lg overflow-hidden border border-studio-800 bg-studio-900/60 max-h-36 flex items-center justify-center">
                    <img
                      src={activeRecord.renderPreviewDataUrl}
                      alt="Render Preview"
                      className="w-full object-contain max-h-36"
                    />
                  </div>
                )}

                {/* Critique Summary */}
                <div className="text-xs text-studio-300 leading-relaxed bg-studio-900/70 p-2.5 rounded-lg border border-studio-850">
                  <span className="font-semibold text-roblox-blue">Vision Evaluator: </span>
                  {activeRecord.critique.summary}
                </div>

                {/* Detected Problems List */}
                {activeRecord.critique.items && activeRecord.critique.items.length > 0 && (
                  <div className="space-y-1.5">
                    <div className="text-[11px] font-medium text-studio-400">
                      Detected Flaws / Discrepancies ({activeRecord.critique.items.length}):
                    </div>
                    <div className="space-y-1.5">
                      {activeRecord.critique.items.map((item, idx) => (
                        <div
                          key={idx}
                          className="flex items-start gap-2 text-xs bg-studio-900 p-2 rounded-lg border border-studio-800/80"
                        >
                          <AlertCircle
                            className={`w-3.5 h-3.5 mt-0.5 shrink-0 ${
                              item.severity === 'high'
                                ? 'text-roblox-red'
                                : item.severity === 'medium'
                                ? 'text-roblox-yellow'
                                : 'text-studio-400'
                            }`}
                          />
                          <div className="space-y-0.5">
                            <div className="text-studio-200">{item.description}</div>
                            <div className="text-[10px] font-mono text-roblox-blue">
                              Action: {item.suggestedAction}
                              {item.targetPartName ? ` (${item.targetPartName})` : ''}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Applied Modifications */}
                {activeRecord.appliedModifications && activeRecord.appliedModifications.length > 0 && (
                  <div className="space-y-1">
                    <div className="text-[11px] font-medium text-studio-400">
                      Applied Corrections:
                    </div>
                    <ul className="space-y-1 text-xs">
                      {activeRecord.appliedModifications.map((mod, i) => (
                        <li key={i} className="flex items-center gap-1.5 text-roblox-green">
                          <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
                          <span className="text-studio-300 text-[11px] truncate">{mod}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}

            {/* Improve / Refine Button */}
            {onImproveFurther && (
              <button
                type="button"
                onClick={onImproveFurther}
                disabled={isGenerating}
                className="w-full py-2.5 px-3 bg-studio-800 hover:bg-studio-750 text-studio-100 rounded-xl text-xs font-semibold flex items-center justify-center gap-2 border border-studio-700 transition"
              >
                <Wand2 className="w-3.5 h-3.5 text-roblox-blue" />
                <span>Trigger Next Self-Improvement Loop</span>
              </button>
            )}
          </div>
        )}

        {/* TAB 2: SCENE GRAPH TREE EXPLORER */}
        {activeTab === 'scene_graph' && (
          <div className="space-y-3">
            <div className="bg-studio-950 p-3 rounded-xl border border-studio-800 space-y-2">
              <div className="flex items-center justify-between pb-2 border-b border-studio-850">
                <span className="text-xs font-semibold text-studio-200">Scene Hierarchy</span>
                <span className="text-[11px] text-studio-500 font-mono">
                  {currentModel?.instances?.length || 0} Instances
                </span>
              </div>

              <div className="space-y-1 text-xs">
                <div className="font-semibold text-roblox-blue flex items-center justify-between py-1">
                  <div className="flex items-center gap-1">
                    <ChevronDown className="w-3.5 h-3.5" />
                    <span>{currentModel?.name || 'Model'}</span>
                  </div>
                  {currentModel?.primaryPartId && (
                    <span className="text-[10px] text-studio-400 font-mono bg-studio-900 px-1.5 py-0.5 rounded border border-studio-800">
                      PrimaryPart: {currentModel.primaryPartId}
                    </span>
                  )}
                </div>

                <div className="pl-3 space-y-1 border-l border-studio-800 ml-2 max-h-60 overflow-y-auto">
                  {currentModel?.instances.map((inst, idx) => {
                    const part = inst as RobloxPartIR;
                    const isSelected = selectedPartId === part.id;
                    const isPrimary = currentModel.primaryPartId === part.id;
                    return (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => setSelectedPartId(isSelected ? null : part.id)}
                        className={`w-full text-left p-1.5 rounded transition flex items-center justify-between text-xs ${
                          isSelected
                            ? 'bg-roblox-blue/20 border border-roblox-blue/60 text-white'
                            : 'bg-studio-900/80 hover:bg-studio-850 text-studio-200 border border-transparent'
                        }`}
                      >
                        <div className="flex items-center gap-1.5 truncate">
                          <span
                            className="w-2.5 h-2.5 rounded-full shrink-0 border border-black/30"
                            style={{
                              backgroundColor: part.color
                                ? `rgb(${part.color[0]}, ${part.color[1]}, ${part.color[2]})`
                                : '#888',
                            }}
                          />
                          <span className="font-medium truncate">{part.name}</span>
                          {isPrimary && (
                            <span className="text-[9px] bg-roblox-blue/30 text-roblox-blue px-1 rounded">
                              ★
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-1.5 shrink-0">
                          <span className="text-[10px] font-mono text-studio-400 bg-studio-950 px-1 py-0.5 rounded">
                            {part.material || 'Part'}
                          </span>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Selected Part Property Inspector */}
            {selectedPart ? (
              <div className="bg-studio-950 p-3.5 rounded-xl border border-roblox-blue/40 space-y-2.5 text-xs animate-in fade-in duration-200">
                <div className="flex items-center justify-between pb-2 border-b border-studio-850">
                  <div className="flex items-center gap-1.5">
                    <Box className="w-3.5 h-3.5 text-roblox-blue" />
                    <span className="font-bold text-studio-100">{selectedPart.name}</span>
                    <span className="text-[10px] text-studio-500 font-mono">({selectedPart.className})</span>
                  </div>
                  <button
                    onClick={() => setSelectedPartId(null)}
                    className="text-[10px] text-studio-400 hover:text-studio-200 px-1.5 py-0.5 rounded bg-studio-900"
                  >
                    Deselect
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-2 text-[11px]">
                  {/* Size */}
                  <div className="bg-studio-900/80 p-2 rounded border border-studio-850">
                    <span className="text-studio-400 block text-[10px]">Size (studs):</span>
                    <span className="font-mono text-studio-200 font-semibold">
                      {selectedPart.size?.map((v) => Number(v).toFixed(1)).join(' × ')}
                    </span>
                  </div>

                  {/* Position */}
                  <div className="bg-studio-900/80 p-2 rounded border border-studio-850">
                    <span className="text-studio-400 block text-[10px]">Position:</span>
                    <span className="font-mono text-studio-200 font-semibold">
                      [{selectedPart.position?.map((v) => Number(v).toFixed(1)).join(', ')}]
                    </span>
                  </div>

                  {/* Material */}
                  <div className="bg-studio-900/80 p-2 rounded border border-studio-850">
                    <span className="text-studio-400 block text-[10px]">Material:</span>
                    <span className="font-mono text-roblox-blue font-semibold">
                      {selectedPart.material || 'SmoothPlastic'}
                    </span>
                  </div>

                  {/* Color Swatch */}
                  <div className="bg-studio-900/80 p-2 rounded border border-studio-850 flex items-center justify-between">
                    <div>
                      <span className="text-studio-400 block text-[10px]">Color:</span>
                      <span className="font-mono text-studio-200 font-semibold text-[10px]">
                        {selectedPart.color ? `rgb(${selectedPart.color.join(',')})` : 'Default'}
                      </span>
                    </div>
                    {selectedPart.color && (
                      <div
                        className="w-5 h-5 rounded-md border border-white/20 shadow-sm"
                        style={{
                          backgroundColor: `rgb(${selectedPart.color[0]}, ${selectedPart.color[1]}, ${selectedPart.color[2]})`,
                        }}
                      />
                    )}
                  </div>
                </div>

                {/* Physics & Flags */}
                <div className="flex flex-wrap gap-1.5 pt-1">
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-mono ${
                      selectedPart.anchored !== false
                        ? 'bg-roblox-green/20 text-roblox-green border border-roblox-green/30'
                        : 'bg-studio-850 text-studio-400'
                    }`}
                  >
                    Anchored: {selectedPart.anchored !== false ? 'True' : 'False'}
                  </span>
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-mono ${
                      selectedPart.canCollide !== false
                        ? 'bg-roblox-blue/20 text-roblox-blue border border-roblox-blue/30'
                        : 'bg-studio-850 text-studio-400'
                    }`}
                  >
                    CanCollide: {selectedPart.canCollide !== false ? 'True' : 'False'}
                  </span>
                  {selectedPart.transparency ? (
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-purple-500/20 text-purple-300 border border-purple-500/30">
                      Transparency: {selectedPart.transparency}
                    </span>
                  ) : null}
                </div>
              </div>
            ) : (
              <div className="text-center p-3 text-studio-500 text-xs bg-studio-950/60 rounded-xl border border-studio-850/60">
                Click any part in the tree above to inspect its 3D properties and dimensions.
              </div>
            )}
          </div>
        )}

        {/* TAB 3: DOWNLOAD & EXPORT */}
        {activeTab === 'export' && (
          <div className="space-y-3">
            <div className="bg-studio-950 p-3.5 rounded-xl border border-studio-800 space-y-3">
              <div>
                <h3 className="text-xs font-semibold text-studio-100 flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-roblox-blue" />
                  Roblox Studio Production Export
                </h3>
                <p className="text-[11px] text-studio-400 leading-relaxed mt-1">
                  Download or paste directly into Roblox Studio. Every asset is verified for valid
                  CFrames, Part hierarchies, and materials.
                </p>
              </div>

              {/* 1-Click Lua Script Copy (Command Bar) */}
              <div className="bg-gradient-to-r from-blue-950/60 to-purple-950/60 border border-roblox-blue/40 rounded-xl p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-xs font-bold text-white">
                    <Terminal className="w-4 h-4 text-roblox-blue" />
                    <span>Instant Studio Command Bar</span>
                  </div>
                  <span className="text-[9px] bg-roblox-blue text-white px-1.5 py-0.5 rounded font-mono font-bold tracking-wider uppercase">
                    No Files Needed
                  </span>
                </div>
                <p className="text-[11px] text-studio-300">
                  Open Roblox Studio, press <kbd className="px-1 py-0.5 bg-studio-900 border border-studio-700 rounded text-[10px] font-mono">View &gt; Command Bar</kbd>, paste this script, and press Enter to instantly spawn!
                </p>
                <div className="flex gap-2 pt-1">
                  <button
                    onClick={handleCopyLuaScript}
                    className="flex-1 py-2 px-3 bg-roblox-blue hover:bg-roblox-blue/90 text-white rounded-lg text-xs font-bold flex items-center justify-center gap-1.5 shadow transition"
                  >
                    {copiedLua ? (
                      <>
                        <Check className="w-4 h-4 text-white" />
                        <span>Copied Lua Script!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        <span>Copy Studio Lua Script</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => setShowLuaPreview(!showLuaPreview)}
                    className="py-2 px-2.5 bg-studio-900 hover:bg-studio-850 text-studio-300 rounded-lg text-xs font-medium border border-studio-750 transition flex items-center gap-1"
                    title="Toggle Script Preview"
                  >
                    <Code2 className="w-3.5 h-3.5" />
                    <span>{showLuaPreview ? 'Hide' : 'Preview'}</span>
                  </button>
                </div>

                {/* Optional Expandable Lua Code Preview */}
                {showLuaPreview && currentModel && (
                  <div className="mt-2 p-2 bg-studio-950 rounded-lg border border-studio-800 text-[10px] font-mono text-studio-300 max-h-48 overflow-y-auto">
                    <pre className="whitespace-pre-wrap">{generateRobloxLuaScript(currentModel)}</pre>
                  </div>
                )}
              </div>

              {/* .rbxmx XML Download */}
              <button
                onClick={() => handleDownload('rbxmx')}
                disabled={downloadingFormat === 'rbxmx'}
                className="w-full py-2.5 px-3 bg-studio-850 hover:bg-studio-800 text-studio-100 rounded-lg text-xs font-semibold flex items-center justify-between border border-studio-750 transition shadow"
              >
                <div className="flex items-center gap-2">
                  <Download className="w-4 h-4 text-roblox-blue" />
                  <span>Download .rbxmx (Roblox XML Model)</span>
                </div>
                <span className="text-[10px] text-roblox-blue uppercase tracking-wider font-mono font-bold">
                  Recommended
                </span>
              </button>

              {/* .rbxm Binary Download */}
              <button
                onClick={() => handleDownload('rbxm')}
                disabled={downloadingFormat === 'rbxm'}
                className="w-full py-2.5 px-3 bg-studio-900 hover:bg-studio-850 text-studio-200 rounded-lg text-xs font-medium flex items-center justify-between border border-studio-800 transition"
              >
                <div className="flex items-center gap-2">
                  <Download className="w-4 h-4 text-studio-400" />
                  <span>Download .rbxm (Roblox Binary)</span>
                </div>
                <span className="text-[10px] text-studio-500 uppercase tracking-wider font-mono">
                  Binary
                </span>
              </button>

              {/* Copy / Export JSON IR */}
              <div className="pt-2 border-t border-studio-850 flex gap-2">
                <button
                  onClick={() => handleDownload('json')}
                  className="flex-1 py-2 px-2.5 bg-studio-900 hover:bg-studio-850 text-studio-300 rounded-lg text-xs font-medium flex items-center justify-center gap-1.5 border border-studio-800 transition"
                >
                  <FileCode className="w-3.5 h-3.5" />
                  <span>Download JSON IR</span>
                </button>
                <button
                  onClick={handleCopyJson}
                  className="py-2 px-3 bg-studio-900 hover:bg-studio-850 text-studio-300 rounded-lg text-xs font-medium flex items-center justify-center gap-1.5 border border-studio-800 transition"
                >
                  {copiedJson ? <Check className="w-3.5 h-3.5 text-roblox-green" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedJson ? 'Copied!' : 'Copy JSON'}</span>
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
