// ============================================================
// Roblox Asset AI - Frontier LLM Thinking Provider
// Dynamic 3D Spatial Reasoning & Synthesis using Frontier 70B Models
// Supports OpenRouter, Groq, Cerebras, DeepInfra, SambaNova, Together, Mistral
// ============================================================

import fs from 'fs';
import path from 'path';
import { AIProvider, AssetPlan, VisionInspectionRequest } from './types';
import {
  RobloxModelIR,
  RobloxAnimationIR,
  IterationCritique,
  AssetType,
  RobloxPartIR,
  RobloxInstanceIR,
} from '../types/roblox';
import { ProceduralProvider } from './procedural-provider';
import { autoRigModel } from '../roblox/auto-rigger';
import { ReferenceRetriever } from './knowledge/reference-retriever';

interface LLMRoute {
  id: string;
  name: string;
  url: string;
  model: string;
  apiKey: string;
  headers?: Record<string, string>;
}

// Global state across requests in the server process
const routeCooldowns = new Map<string, number>();

export class FrontierThinkingProvider implements AIProvider {
  public readonly providerName = 'Frontier 70B Thinking Engine';
  private fallback: ProceduralProvider;

  constructor() {
    this.fallback = new ProceduralProvider();
  }

  private getAllKeys(envVarName: string): string[] {
    const raw = process.env[envVarName];
    if (!raw) return [];
    return raw.split(',').map((s) => s.trim()).filter(Boolean);
  }

  /**
   * Reads the probed Top 5 models generated by scripts/key_rotator.py or main.py
   */
  private readActiveRoutesFromFile(): LLMRoute[] | null {
    try {
      const candidates = [
        path.join(process.cwd(), 'active_routes.json'),
        path.join(__dirname, '../../../../active_routes.json'),
      ];
      for (const p of candidates) {
        if (fs.existsSync(p)) {
          const raw = fs.readFileSync(p, 'utf-8');
          const parsed = JSON.parse(raw);
          if (Array.isArray(parsed) && parsed.length > 0) {
            return parsed.map((r: any) => ({
              id: r.id,
              name: r.name,
              url: r.url,
              model: r.model,
              apiKey: r.apiKey,
              headers: r.headers || { 'User-Agent': 'RobloxAssetAI/1.0' },
            }));
          }
        }
      }
    } catch {
      // Ignore file error and fallback
    }
    return null;
  }

  private buildAvailableRoutes(): LLMRoute[] {
    // 1. Try reading the verified Top 5 routes from file
    const fileRoutes = this.readActiveRoutesFromFile();
    if (fileRoutes && fileRoutes.length > 0) {
      return fileRoutes;
    }

    // 2. Fallback: Dynamically assemble from environment variables across all providers
    const routes: LLMRoute[] = [];

    const groqKeys = Array.from(new Set([
      ...this.getAllKeys('GROQ_API_KEYS'),
      ...(process.env.GROQ_API_KEY ? [process.env.GROQ_API_KEY.trim()] : [])
    ]));

    for (let i = 0; i < groqKeys.length; i++) {
      const k = groqKeys[i];
      routes.push({
        id: `groq_k${i + 1}_qwen27b`,
        name: `Groq Key #${i + 1} [Qwen-3.8-27B]`,
        url: 'https://api.groq.com/openai/v1/chat/completions',
        model: 'qwen/qwen3.8-27b',
        apiKey: k,
        headers: { 'User-Agent': 'RobloxAssetAI/1.0' },
      });
      routes.push({
        id: `groq_k${i + 1}_gpt120b`,
        name: `Groq Key #${i + 1} [GPT-OSS-120B]`,
        url: 'https://api.groq.com/openai/v1/chat/completions',
        model: 'openai/gpt-oss-120b',
        apiKey: k,
        headers: { 'User-Agent': 'RobloxAssetAI/1.0' },
      });
    }

    const mistralKeys = Array.from(new Set([
      ...this.getAllKeys('MISTRAL_API_KEYS'),
      ...(process.env.MISTRAL_API_KEY ? [process.env.MISTRAL_API_KEY.trim()] : [])
    ]));

    for (let i = 0; i < mistralKeys.length; i++) {
      const k = mistralKeys[i];
      routes.push({
        id: `mistral_k${i + 1}_codestral`,
        name: `Mistral Key #${i + 1} [Codestral-Latest]`,
        url: 'https://api.mistral.ai/v1/chat/completions',
        model: 'codestral-latest',
        apiKey: k,
        headers: { 'User-Agent': 'RobloxAssetAI/1.0' },
      });
    }

    const openrouterKeys = Array.from(new Set([
      ...this.getAllKeys('OPENROUTER_API_KEYS'),
      ...(process.env.OPENROUTER_API_KEY ? [process.env.OPENROUTER_API_KEY.trim()] : [])
    ]));

    for (let i = 0; i < openrouterKeys.length; i++) {
      const k = openrouterKeys[i];
      routes.push({
        id: `openrouter_k${i + 1}_llama70b`,
        name: `OpenRouter Key #${i + 1} [Llama-3.3-70B]`,
        url: 'https://openrouter.ai/api/v1/chat/completions',
        model: 'meta-llama/llama-3.3-70b-instruct',
        apiKey: k,
        headers: {
          'User-Agent': 'RobloxAssetAI/1.0',
          'HTTP-Referer': 'https://roblox-asset-ai.local',
          'X-Title': 'Roblox Asset AI',
        },
      });
      routes.push({
        id: `openrouter_k${i + 1}_deepseek`,
        name: `OpenRouter Key #${i + 1} [DeepSeek-Chat]`,
        url: 'https://openrouter.ai/api/v1/chat/completions',
        model: 'deepseek/deepseek-chat',
        apiKey: k,
        headers: {
          'User-Agent': 'RobloxAssetAI/1.0',
          'HTTP-Referer': 'https://roblox-asset-ai.local',
          'X-Title': 'Roblox Asset AI',
        },
      });
    }

    return routes;
  }

  /**
   * Strictly sequential route execution:
   * Always tries Route #1 first. If rate-limited (429), immediately tries Route #2, then #3, #4, #5.
   * Once Route #1 cooldown expires (60s), subsequent requests try Route #1 first again.
   */
  private async executeLLMCascade(
    systemPrompt: string,
    userPrompt: string,
    temperature = 0.3,
    maxTokens = 2500
  ): Promise<any | null> {
    const allRoutes = this.buildAvailableRoutes();
    if (allRoutes.length === 0) return null;

    const now = Date.now();

    // If every single route is currently in cooldown, clear Route #1 cooldown to re-attempt primary
    const allCooled = allRoutes.every((r) => (routeCooldowns.get(r.id) || 0) > now);
    if (allCooled) {
      console.warn('[FrontierAI] All routes are currently in cooldown. Re-attempting primary Route #1...');
      routeCooldowns.delete(allRoutes[0].id);
    }

    // Strictly sequential: iterate in priority order (Route #1 -> #2 -> #3 -> #4 -> #5)
    for (let i = 0; i < allRoutes.length; i++) {
      const route = allRoutes[i];
      const cd = routeCooldowns.get(route.id) || 0;

      if (cd > now) {
        const remaining = Math.ceil((cd - now) / 1000);
        console.log(`[FrontierAI] ⏳ [Route #${i + 1}/${allRoutes.length}] ${route.name} is cooling down (${remaining}s remaining). Skipping to next key...`);
        continue; // Rollover to next route in list
      }

      let timeout: any = null;
      try {
        console.log(`[FrontierAI] 🎯 [Route #${i + 1}/${allRoutes.length}] Trying ${route.name} (${route.model})...`);
        const controller = new AbortController();
        timeout = setTimeout(() => controller.abort(), 25000); // 25s total timeout

        const response = await fetch(route.url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${route.apiKey}`,
            ...(route.headers || {}),
          },
          body: JSON.stringify({
            model: route.model,
            response_format: { type: 'json_object' },
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userPrompt },
            ],
            temperature,
            max_tokens: maxTokens,
          }),
          signal: controller.signal,
        });

        if (!response.ok) {
          const errText = await response.text();
          clearTimeout(timeout);
          if (response.status === 429) {
            const nextDesc = i + 1 < allRoutes.length ? `Route #${i + 2} (${allRoutes[i + 1].name})` : 'fallback';
            console.warn(`[FrontierAI] ⚠️ Route #${i + 1} (${route.name}) hit rate limit (429)! Setting 60s cooldown & rolling over to ${nextDesc}...`);
            routeCooldowns.set(route.id, Date.now() + 60000);
            continue; // Immediately attempts next route!
          } else if (response.status === 402 || response.status === 401) {
            console.warn(`[FrontierAI] ⚠️ Route #${i + 1} (${route.name}) quota/auth error (${response.status}). Setting 30m cooldown & rolling over...`);
            routeCooldowns.set(route.id, Date.now() + 1800000);
            continue;
          } else {
            console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) returned HTTP ${response.status}: ${errText.slice(0, 120)}. Rolling over to next route...`);
            continue;
          }
        }

        const data = await response.json();
        clearTimeout(timeout);
        const rawContent = data.choices?.[0]?.message?.content;
        if (!rawContent) {
          console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) returned empty content. Rolling over...`);
          continue;
        }

        let clean = rawContent.trim();
        if (clean.includes('```json')) {
          clean = clean.split('```json')[1].split('```')[0].trim();
        } else if (clean.includes('```')) {
          clean = clean.split('```')[1].split('```')[0].trim();
        } else {
          const s = clean.indexOf('{');
          const e = clean.lastIndexOf('}');
          if (s !== -1 && e !== -1 && e > s) {
            clean = clean.slice(s, e + 1);
          }
        }

        const parsed = JSON.parse(clean);
        console.log(`[FrontierAI] ✅ Generation succeeded using Route #${i + 1} [${route.name}]`);
        // Clear any cooldown on this successful route
        routeCooldowns.delete(route.id);
        return parsed;
      } catch (err: any) {
        if (timeout) clearTimeout(timeout);
        console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) error/timeout (${err.message || err}). Rolling over to next route...`);
        routeCooldowns.set(route.id, Date.now() + 20000);
      }
    }

    console.warn('[FrontierAI] All available LLM routes exhausted. Falling back to domain synthesis.');
    return null;
  }

  public async planAsset(
    prompt: string,
    referenceImage?: string,
    assetType: AssetType = 'model'
  ): Promise<AssetPlan> {
    // Fast, local domain planning without an extra LLM network roundtrip.
    // Preserves API token quota and rate limits exclusively for genuine 3D model geometry synthesis.
    return this.fallback.planAsset(prompt, referenceImage, assetType);
  }

  public async generateModelIR(
    plan: AssetPlan,
    prompt: string,
    referenceImage?: string,
    iteration = 1
  ): Promise<RobloxModelIR> {
    const systemPrompt = `You are Roblox Asset AI, the world's most advanced neural 3D modeling and rigging engine for Roblox Studio.
You do NOT use generic approximations, placeholders, or simplistic 5-block shapes. You deeply comprehend Roblox geometry, stud units, physical grounding, part hierarchies, material palettes, and Motor6D rigging standards.

ROBLOX STUDIO ENGINE STANDARDS:
- UNITS: 1 stud ≈ 0.28 meters. Standard avatar height is 5 studs.
- COORDINATES: Y is UP (Y=0 is baseplate ground). X is lateral (-X left, +X right). Z is depth (-Z back, +Z forward).
- PART BUDGET: Always construct between 20 and 45 distinct parts to guarantee rich silhouette, structural depth, and micro-detailing.
- ANTI-Z-FIGHTING: Offset layered parts (clothing panels, belts, lapels, armor plates, trim, decals) by +0.02 to +0.05 studs on surface axes to eliminate texture flickering!

HIERARCHICAL 5-LAYER GEOMETRY COMPOSITION:
1. LAYER 1: STRUCTURAL FOUNDATION & GROUNDING
   - Base/chassis/feet firmly grounded at Y=0.
   - Designate a clear "primaryPartId" (e.g. Torso for characters, Chassis for vehicles, Base for props).
2. LAYER 2: ANATOMICAL / MECHANICAL ARTICULATION
   - Distinct limbs, joints, cockpit, wings, wheels, or pillars connected cohesively.
   - For Humanoids / Characters / Zombies:
     * Core parts named EXACTLY: "Torso" [2,2,1 at Y=3.0], "Head" [1.2,1.2,1.2 at Y=4.6], "LeftArm" [1,2,1 at X=-1.5, Y=3.0], "RightArm" [1,2,1 at X=1.5, Y=3.0], "LeftLeg" [1,2,1 at X=-0.5, Y=1.0], "RightLeg" [1,2,1 at X=0.5, Y=1.0].
3. LAYER 3: THEMATIC CLOTHING, ARMOR, PANELS & SILHOUETTE
   - For characters & zombies:
     * Layered garments: Undershirts, jackets, vests, lapels, neckties, collars, belts with brass/metal buckles, ripped fabric cuffs, shoes/boots with soles.
     * Decayed / undead: Sunken glowing eyes (Neon), snarling jaws, exposed ribs, torn fabric edges, rotting skin tones [85, 125, 75].
   - For vehicles: Windshields (Glass, transparency 0.4), roll cages, bumpers, exhausts, spoilers, headlights (Neon).
   - For weapons: Crossguards, grips, pommels, blades with beveled wedge tips.
4. LAYER 4: HELD PROPS & ACCESSORIES (CRITICAL)
   - When the prompt requests a held or equipped item (e.g. "holding a torn briefcase", "wielding a sword", "holding a lantern"):
     * MODEL THE ITEM IN COMPLETE MULTI-PART DETAIL!
     * Position it directly at or attached to the hand/arm (e.g. RightArm hand level Y=1.4 to 2.2)!
     * Example briefcase: Briefcase body, brass arched handle, left/right locking latches, corner metal plates.
5. LAYER 5: MATERIAL HARMONIZATION & ACCENT HIGHLIGHTS
   - NEVER use flat monochrome. Harmonize textures:
     * Fabric for clothing/leather
     * SmoothPlastic for skin/surfaces
     * Metal for buckles, latches, blades, engines, rims
     * Neon for glowing eyes, magical runes, laser barrels, embers
     * Glass for windshields and bottles
     * Wood / WoodPlanks for timber, crates, tables

OUTPUT JSON SCHEMA:
{
  "assetType": "model",
  "name": "DescriptiveModelName",
  "primaryPartId": "id_of_root_or_torso_part",
  "instances": [
    {
      "id": "unique_str",
      "name": "PascalCaseName",
      "className": "Part" | "WedgePart",
      "shape": "Block" | "Ball" | "Cylinder" | "Wedge",
      "size": [width, height, depth],
      "position": [x, y, z],
      "rotation": [pitch, yaw, roll],
      "color": [r, g, b],
      "material": "SmoothPlastic"|"Neon"|"Fabric"|"Metal"|"WoodPlanks"|"Wood"|"Cobblestone"|"Glass"|"Brick",
      "transparency": 0.0,
      "anchored": true,
      "canCollide": true
    }
  ]
}
Return JSON ONLY. No markdown conversational text.`;

    // Fetch relevant reference blueprint for in-context few-shot learning
    const referenceContext = ReferenceRetriever.formatReferenceForPrompt(prompt);

    let userPrompt = `User Prompt: "${prompt}"
Iteration: ${iteration}
Construct a complete, production-grade 3D Roblox model matching this exact request.
${referenceContext}
CRITICAL INSTRUCTION: Analyze the reference blueprint above for part naming, stud proportions, material contrast, and micro-detailing. Synthesize a brand-new custom model specifically tailored to the user's prompt ("${prompt}"). If the prompt specifies a held item or costume details, include all of them with full structural parts.`;

    if (iteration > 1 && plan) {
      userPrompt += `\nCritique and Refinement: Add supplementary accent parts, enhance micro-details, improve material contrast, and fix any misalignment from earlier passes.`;
    }

    const result = await this.executeLLMCascade(systemPrompt, userPrompt, 0.35, 4000);

    if (result && Array.isArray(result.instances) && result.instances.length > 0) {
      const sanitized = this.sanitizeModel(result, prompt, iteration);
      return autoRigModel(sanitized, prompt).model;
    }

    // Fallback to domain knowledge if cascade was unreachable
    const fallbackModel = await this.fallback.generateModelIR(plan, prompt, referenceImage, iteration);
    return autoRigModel(fallbackModel, prompt).model;
  }

  public async generateAnimationIR(
    prompt: string,
    modelIR: RobloxModelIR,
    referenceImage?: string
  ): Promise<RobloxAnimationIR> {
    const systemPrompt = `You are Roblox Asset AI's Master Keyframe Animation Director.
Synthesize a fluid, organic, Disney-quality keyframe animation sequence for Roblox Studio R6 avatar rigs.
Target rig bones: "Torso" (root/waist), "Head" (neck), "LeftArm" (left shoulder), "RightArm" (right shoulder), "LeftLeg" (left hip), "RightLeg" (right hip).

KINETIC PRINCIPLES & ROBOTIC-FREE DYNAMICS:
1. ANTICIPATION: Subtle reverse coil before forceful movements (e.g. leaning back before a sword slash or forward shamble).
2. SECONDARY MOTION & COUNTER-BALANCE: When arms swing forward, torso rotates slightly; when right leg steps forward, left arm swings forward.
3. ORGANIC SPINAL MOTION: Animate the "Torso" with vertical displacement (bounce: position [0, y, 0]) and rotation (pitch/roll/yaw) to make the character look alive, never stiff!
4. SMOOTH CURVES: Generate 5 to 9 keyframes evenly distributed across the animation length (1.2 to 2.4 seconds).
5. EASING: Use "Sine", "Quad", or "Cubic" with "InOut" or "Out" for natural physical inertia and deceleration.

OUTPUT JSON SCHEMA:
{
  "assetType": "animation",
  "name": "DescriptiveAnimationName",
  "length": 1.6,
  "loop": true,
  "priority": "Movement" | "Action",
  "fps": 30,
  "keyframes": [
    {
      "time": 0.0,
      "name": "Keyframe_0",
      "poses": [
        { "boneName": "Torso", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "Head", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "LeftArm", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "RightArm", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "LeftLeg", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "RightLeg", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" }
      ]
    }
  ]
}
Return valid JSON only.`;

    const userPrompt = `Generate a high-quality Roblox character animation sequence for: "${prompt}".`;
    const anim = await this.executeLLMCascade(systemPrompt, userPrompt, 0.3, 2500);

    if (anim && Array.isArray(anim.keyframes) && anim.keyframes.length >= 2) {
      return {
        assetType: 'animation',
        name: anim.name || 'CustomMotion',
        length: typeof anim.length === 'number' ? anim.length : 1.6,
        loop: anim.loop ?? true,
        priority: anim.priority || 'Action',
        fps: anim.fps || 30,
        keyframes: anim.keyframes,
        metadata: {
          prompt,
          generator: this.providerName,
        },
      };
    }

    return this.fallback.generateAnimationIR(prompt, modelIR, referenceImage);
  }

  public async inspectAndCritique(request: VisionInspectionRequest): Promise<IterationCritique> {
    // Fast, deterministic local structural & aesthetic evaluation
    // (bounding boxes, grounding, symmetry, and material harmony)
    // Avoids burning remote LLM tokens or triggering 429 rate limits during quality inspection.
    return this.fallback.inspectAndCritique(request);
  }

  /**
   * Sanitizes, repairs, and enforces constraints on LLM-generated Model IR
   */
  private sanitizeModel(raw: any, prompt: string, iteration: number): RobloxModelIR {
    const validShapes = ['Block', 'Ball', 'Cylinder', 'Wedge'];
    const validMaterials = [
      'SmoothPlastic',
      'Neon',
      'Fabric',
      'Metal',
      'WoodPlanks',
      'Wood',
      'Cobblestone',
      'Glass',
      'Brick',
      'DiamondPlate',
      'Granite',
      'Slate',
      'CorrodedMetal',
    ];

    const instances: RobloxInstanceIR[] = [];
    const usedIds = new Set<string>();

    for (let idx = 0; idx < (raw.instances || []).length; idx++) {
      const p = raw.instances[idx];
      let id = p.id ? String(p.id) : `p_${idx}`;
      while (usedIds.has(id)) {
        id = `${id}_${Math.floor(Math.random() * 100)}`;
      }
      usedIds.add(id);

      const shape = validShapes.includes(p.shape) ? p.shape : 'Block';
      const className = shape === 'Wedge' || p.className === 'WedgePart' ? 'WedgePart' : 'Part';
      const material = validMaterials.includes(p.material) ? p.material : 'SmoothPlastic';

      const size: [number, number, number] = Array.isArray(p.size) && p.size.length >= 3
        ? [Math.max(0.1, Number(p.size[0]) || 1), Math.max(0.1, Number(p.size[1]) || 1), Math.max(0.1, Number(p.size[2]) || 1)]
        : [1, 1, 1];

      const position: [number, number, number] = Array.isArray(p.position) && p.position.length >= 3
        ? [Number(p.position[0]) || 0, Number(p.position[1]) || 0, Number(p.position[2]) || 0]
        : [0, idx * 1.5, 0];

      const rotation: [number, number, number] = Array.isArray(p.rotation) && p.rotation.length >= 3
        ? [Number(p.rotation[0]) || 0, Number(p.rotation[1]) || 0, Number(p.rotation[2]) || 0]
        : [0, 0, 0];

      const color: [number, number, number] = Array.isArray(p.color) && p.color.length >= 3
        ? [
            Math.min(255, Math.max(0, Math.round(Number(p.color[0]) || 120))),
            Math.min(255, Math.max(0, Math.round(Number(p.color[1]) || 120))),
            Math.min(255, Math.max(0, Math.round(Number(p.color[2]) || 120))),
          ]
        : [120, 130, 140];

      const part: RobloxPartIR = {
        id,
        name: p.name ? String(p.name).replace(/[^a-zA-Z0-9_]/g, '') : `Part_${idx}`,
        className,
        shape,
        size,
        position,
        rotation,
        color,
        material: material as any,
        anchored: true,
        canCollide: p.canCollide ?? true,
      };

      instances.push(part);
    }

    const primaryPartId = raw.primaryPartId && usedIds.has(raw.primaryPartId)
      ? raw.primaryPartId
      : instances[0]?.id || 'root_part';

    return {
      assetType: 'model',
      name: raw.name ? String(raw.name).replace(/[^a-zA-Z0-9_]/g, '') : 'GeneratedRobloxAsset',
      primaryPartId,
      instances,
      metadata: {
        prompt,
        iteration,
        generator: this.providerName,
      },
    };
  }

  public async applyCritiqueToModel(
    currentModel: RobloxModelIR,
    critique: IterationCritique,
    prompt: string
  ): Promise<RobloxModelIR> {
    const systemPrompt = `You are Roblox Asset AI's 3D Refiner.
Enhance and modify the given Roblox Model IR based on the visual critique.
Add detailed accent parts, improve alignment, enhance color contrast, or fix flaws mentioned in the critique.
Output valid JSON only matching schema:
{
  "assetType": "model",
  "name": "ModelName",
  "primaryPartId": "id",
  "instances": [ ...updated parts... ]
}`;

    const userPrompt = `User Prompt: "${prompt}"\nCurrent Model IR: ${JSON.stringify(currentModel)}\nCritique Summary: "${critique.summary}"\nCritique Items: ${JSON.stringify(critique.items)}\nProduce the improved Roblox Model IR.`;

    const refined = await this.executeLLMCascade(systemPrompt, userPrompt, 0.35, 3500);
    if (refined && Array.isArray(refined.instances) && refined.instances.length > 0) {
      return this.sanitizeModel(refined, prompt, 2);
    }

    return this.fallback.applyCritiqueToModel(currentModel, critique, prompt);
  }

  public async applyCritiqueToAnimation(
    currentAnimation: RobloxAnimationIR,
    critique: IterationCritique,
    prompt: string
  ): Promise<RobloxAnimationIR> {
    return this.fallback.applyCritiqueToAnimation(currentAnimation, critique, prompt);
  }
}
