// ============================================================
// Roblox Asset AI - Frontier LLM Thinking Provider
// Dynamic 3D Spatial Reasoning & Synthesis using Frontier 70B Models
// Supports OpenRouter, Groq, Cerebras, DeepInfra, SambaNova, Together, Mistral
// ============================================================

import fs from 'fs';
import path from 'path';
import { AIProvider, AssetPlan, VisionInspectionRequest } from './types';
import {
  RobloxModelIR,
  RobloxAnimationIR,
  IterationCritique,
  AssetType,
  RobloxPartIR,
  RobloxInstanceIR,
} from '../types/roblox';
import { ProceduralProvider } from './procedural-provider';

interface LLMRoute {
  id: string;
  name: string;
  url: string;
  model: string;
  apiKey: string;
  headers?: Record<string, string>;
}

// Global state across requests in the server process
const routeCooldowns = new Map<string, number>();

export class FrontierThinkingProvider implements AIProvider {
  public readonly providerName = 'Frontier 70B Thinking Engine';
  private fallback: ProceduralProvider;

  constructor() {
    this.fallback = new ProceduralProvider();
  }

  private getAllKeys(envVarName: string): string[] {
    const raw = process.env[envVarName];
    if (!raw) return [];
    return raw.split(',').map((s) => s.trim()).filter(Boolean);
  }

  /**
   * Reads the probed Top 5 models generated by scripts/key_rotator.py or main.py
   */
  private readActiveRoutesFromFile(): LLMRoute[] | null {
    try {
      const candidates = [
        path.join(process.cwd(), 'active_routes.json'),
        path.join(__dirname, '../../../../active_routes.json'),
      ];
      for (const p of candidates) {
        if (fs.existsSync(p)) {
          const raw = fs.readFileSync(p, 'utf-8');
          const parsed = JSON.parse(raw);
          if (Array.isArray(parsed) && parsed.length > 0) {
            return parsed.map((r: any) => ({
              id: r.id,
              name: r.name,
              url: r.url,
              model: r.model,
              apiKey: r.apiKey,
              headers: r.headers || { 'User-Agent': 'RobloxAssetAI/1.0' },
            }));
          }
        }
      }
    } catch {
      // Ignore file error and fallback
    }
    return null;
  }

  private buildAvailableRoutes(): LLMRoute[] {
    // 1. Try reading the verified Top 5 routes from file
    const fileRoutes = this.readActiveRoutesFromFile();
    if (fileRoutes && fileRoutes.length > 0) {
      return fileRoutes;
    }

    // 2. Fallback: Dynamically assemble from environment variables
    const routes: LLMRoute[] = [];

    const groqKeys = Array.from(new Set([
      ...this.getAllKeys('GROQ_API_KEYS'),
      ...(process.env.GROQ_API_KEY ? [process.env.GROQ_API_KEY.trim()] : [])
    ]));

    for (let i = 0; i < groqKeys.length; i++) {
      const k = groqKeys[i];
      routes.push({
        id: `groq_k${i + 1}_qwen27b`,
        name: `Groq Key #${i + 1} [Qwen-3.8-27B]`,
        url: 'https://api.groq.com/openai/v1/chat/completions',
        model: 'qwen/qwen3.8-27b',
        apiKey: k,
        headers: { 'User-Agent': 'RobloxAssetAI/1.0' },
      });
    }

    const openrouterKeys = Array.from(new Set([
      ...this.getAllKeys('OPENROUTER_API_KEYS'),
      ...(process.env.OPENROUTER_API_KEY ? [process.env.OPENROUTER_API_KEY.trim()] : [])
    ]));

    for (let i = 0; i < openrouterKeys.length; i++) {
      const k = openrouterKeys[i];
      routes.push({
        id: `openrouter_k${i + 1}_llama70b`,
        name: `OpenRouter Key #${i + 1} [Llama-3.3-70B]`,
        url: 'https://openrouter.ai/api/v1/chat/completions',
        model: 'meta-llama/llama-3.3-70b-instruct',
        apiKey: k,
        headers: {
          'User-Agent': 'RobloxAssetAI/1.0',
          'HTTP-Referer': 'https://roblox-asset-ai.local',
          'X-Title': 'Roblox Asset AI',
        },
      });
    }

    for (let i = 0; i < groqKeys.length; i++) {
      const k = groqKeys[i];
      routes.push({
        id: `groq_k${i + 1}_gpt120b`,
        name: `Groq Key #${i + 1} [GPT-OSS-120B]`,
        url: 'https://api.groq.com/openai/v1/chat/completions',
        model: 'openai/gpt-oss-120b',
        apiKey: k,
        headers: { 'User-Agent': 'RobloxAssetAI/1.0' },
      });
    }

    return routes;
  }

  /**
   * Strictly sequential route execution:
   * Always tries Route #1 first. If rate-limited (429), immediately tries Route #2, then #3, #4, #5.
   * Once Route #1 cooldown expires (60s), subsequent requests try Route #1 first again.
   */
  private async executeLLMCascade(
    systemPrompt: string,
    userPrompt: string,
    temperature = 0.3,
    maxTokens = 2500
  ): Promise<any | null> {
    const allRoutes = this.buildAvailableRoutes();
    if (allRoutes.length === 0) return null;

    const now = Date.now();

    // If every single route is currently in cooldown, clear Route #1 cooldown to re-attempt primary
    const allCooled = allRoutes.every((r) => (routeCooldowns.get(r.id) || 0) > now);
    if (allCooled) {
      console.warn('[FrontierAI] All routes are currently in cooldown. Re-attempting primary Route #1...');
      routeCooldowns.delete(allRoutes[0].id);
    }

    // Strictly sequential: iterate in priority order (Route #1 -> #2 -> #3 -> #4 -> #5)
    for (let i = 0; i < allRoutes.length; i++) {
      const route = allRoutes[i];
      const cd = routeCooldowns.get(route.id) || 0;

      if (cd > now) {
        const remaining = Math.ceil((cd - now) / 1000);
        console.log(`[FrontierAI] ⏳ [Route #${i + 1}/${allRoutes.length}] ${route.name} is cooling down (${remaining}s remaining). Skipping to next key...`);
        continue; // Rollover to next route in list
      }

      let timeout: any = null;
      try {
        console.log(`[FrontierAI] 🎯 [Route #${i + 1}/${allRoutes.length}] Trying ${route.name} (${route.model})...`);
        const controller = new AbortController();
        timeout = setTimeout(() => controller.abort(), 25000); // 25s total timeout

        const response = await fetch(route.url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${route.apiKey}`,
            ...(route.headers || {}),
          },
          body: JSON.stringify({
            model: route.model,
            response_format: { type: 'json_object' },
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userPrompt },
            ],
            temperature,
            max_tokens: maxTokens,
          }),
          signal: controller.signal,
        });

        if (!response.ok) {
          const errText = await response.text();
          clearTimeout(timeout);
          if (response.status === 429) {
            const nextDesc = i + 1 < allRoutes.length ? `Route #${i + 2} (${allRoutes[i + 1].name})` : 'fallback';
            console.warn(`[FrontierAI] ⚠️ Route #${i + 1} (${route.name}) hit rate limit (429)! Setting 60s cooldown & rolling over to ${nextDesc}...`);
            routeCooldowns.set(route.id, Date.now() + 60000);
            continue; // Immediately attempts next route!
          } else if (response.status === 402 || response.status === 401) {
            console.warn(`[FrontierAI] ⚠️ Route #${i + 1} (${route.name}) quota/auth error (${response.status}). Setting 30m cooldown & rolling over...`);
            routeCooldowns.set(route.id, Date.now() + 1800000);
            continue;
          } else {
            console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) returned HTTP ${response.status}: ${errText.slice(0, 120)}. Rolling over to next route...`);
            continue;
          }
        }

        const data = await response.json();
        clearTimeout(timeout);
        const rawContent = data.choices?.[0]?.message?.content;
        if (!rawContent) {
          console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) returned empty content. Rolling over...`);
          continue;
        }

        let clean = rawContent.trim();
        if (clean.includes('```json')) {
          clean = clean.split('```json')[1].split('```')[0].trim();
        } else if (clean.includes('```')) {
          clean = clean.split('```')[1].split('```')[0].trim();
        } else {
          const s = clean.indexOf('{');
          const e = clean.lastIndexOf('}');
          if (s !== -1 && e !== -1 && e > s) {
            clean = clean.slice(s, e + 1);
          }
        }

        const parsed = JSON.parse(clean);
        console.log(`[FrontierAI] ✅ Generation succeeded using Route #${i + 1} [${route.name}]`);
        // Clear any cooldown on this successful route
        routeCooldowns.delete(route.id);
        return parsed;
      } catch (err: any) {
        if (timeout) clearTimeout(timeout);
        console.warn(`[FrontierAI] Route #${i + 1} (${route.name}) error/timeout (${err.message || err}). Rolling over to next route...`);
        routeCooldowns.set(route.id, Date.now() + 20000);
      }
    }

    console.warn('[FrontierAI] All available LLM routes exhausted. Falling back to domain synthesis.');
    return null;
  }

  public async planAsset(
    prompt: string,
    referenceImage?: string,
    assetType: AssetType = 'model'
  ): Promise<AssetPlan> {
    const systemPrompt = `You are an expert Roblox 3D Architect.
Analyze the user's prompt and formulate an architectural plan for a 3D Roblox Studio asset.
Output valid JSON only with keys:
- name: string (concise PascalCase model name matching the prompt)
- assetType: "${assetType}"
- conceptSummary: string (visual description of what will be built)
- suggestedParts: array of { name: string, role: string, shape: "Block"|"Ball"|"Cylinder"|"Wedge", material: string, colorHint: string, relativePosition: string }
- colorPalette: array of { role: string, rgb: [number, number, number] }
- boundingSize: [number, number, number] (overall dimensions in studs)`;

    const userPrompt = `Asset Request: "${prompt}"\nAsset Type: ${assetType}`;

    const plan = await this.executeLLMCascade(systemPrompt, userPrompt, 0.2, 1000);
    if (plan && plan.name && Array.isArray(plan.suggestedParts)) {
      return plan as AssetPlan;
    }

    return this.fallback.planAsset(prompt, referenceImage, assetType);
  }

  public async generateModelIR(
    plan: AssetPlan,
    prompt: string,
    referenceImage?: string,
    iteration = 1
  ): Promise<RobloxModelIR> {
    const systemPrompt = `You are Roblox Asset AI, the premier neural 3D modeling engine for Roblox Studio.
You do NOT use generic approximations or pre-baked templates. You deeply analyze the user's prompt and construct a rich, highly intricate 3D model composed of genuine Roblox primitive parts.

HIERARCHICAL 5-LAYER ARCHITECTURAL BLUEPRINT:
1. LAYER 1: STRUCTURAL CORE / CHASSIS / SKELETON
   - Grounded mass (lowest parts touch Y=0 or floor).
   - Solid foundational proportions with a clear primary anchor part (assign primaryPartId).
2. LAYER 2: ANATOMICAL / MECHANICAL ARTICULATION
   - Distinct limbs, joints, cabin, wings, wheels, or pillars connected cohesively.
3. LAYER 3: THEMATIC DETAILING, CLOTHING, ARMOR & SILHOUETTE
   - For characters, creatures, or zombies:
     * NEVER emit just 5 or 6 bare blocks.
     * Decompose clothing and anatomy: Head with face/jaw/hair/eyes, torso with layered vest/jacket/lapels/necktie/belt, limbs with ripped fabric cuffs, torn sleeves, exposed bones, boots/shoes with soles.
     * For zombies/undead: Haggard shredded business suit with contrasting jacket panels, dangling torn tie, jagged sleeve cuffs, rotting skin tone [85, 125, 75], hollow sunken eyes (Neon), hunched spine.
   - For vehicles: Fenders, cabin glass, spoilers, grille, headlights (Neon), exhausts, bumpers, roll cage.
   - For weapons: Crossguard quillons, fuller blood-groove, pommel weight, grip wraps, blade bevels.
   - For props & architecture: Trim moldings, brackets, rivets, hinges, locks, handles, crenellations.
4. LAYER 4: HELD PROPS, ACCESSORIES & STORYTELLING ELEMENTS
   - If the user prompt requests a held item (e.g. "holding a torn briefcase", "wielding a glowing blade"):
     * Model the item in full detail! (e.g. briefcase body, gold latch, arched handle, metal corners, papers poking out)
     * Position it directly in or attached to the hand/arm!
5. LAYER 5: MATERIAL HARMONIZATION & NEON HIGHLIGHTS
   - Multi-material contrast: Use Fabric for cloth, Metal for latches/hardware, Wood/WoodPlanks for timber, SmoothPlastic for clean surfaces, Glass for transparency, and strategic Neon for glowing eyes/energy cores/runes.
   - Scale part budget: construct 18 to 45 distinct parts for rich silhouette, depth, and unmistakable fidelity.
   - Offset surface trim and decals by +0.02 to +0.05 studs to prevent coplanar z-fighting!

COORDINATE RULES:
- Units are in Roblox studs (1 stud ≈ 0.28m).
- Y is UP (Y=0 is baseplate).
- X is horizontal lateral (-X left, +X right).
- Z is depth (-Z backward, +Z forward).
- Humanoid (R6 standard baseline):
  * Torso: [2, 2, 1] at Y=3.0 (from waist Y=2 to neck Y=4).
  * Head: [1.2, 1.2, 1.2] at Y=4.6.
  * Left Arm: [1, 2, 1] at X=-1.5, Y=3.0. For zombies: pitch forward 75-90 deg!
  * Right Arm: [1, 2, 1] at X=1.5, Y=3.0. For zombies: pitch forward 75-90 deg!
  * Left Leg: [1, 2, 1] at X=-0.5, Y=1.0.
  * Right Leg: [1, 2, 1] at X=0.5, Y=1.0.

PART SCHEMA:
Each item in "instances" MUST be:
{
  "id": "unique_str",
  "name": "PascalCaseName",
  "className": "Part" | "WedgePart",
  "shape": "Block" | "Ball" | "Cylinder" | "Wedge",
  "size": [width, height, depth],
  "position": [x, y, z],
  "rotation": [pitch, yaw, roll],
  "color": [r, g, b],
  "material": "SmoothPlastic"|"Neon"|"Fabric"|"Metal"|"WoodPlanks"|"Wood"|"Cobblestone"|"Glass"|"Brick"|"DiamondPlate",
  "anchored": true,
  "canCollide": true
}

OUTPUT SCHEMA:
{
  "assetType": "model",
  "name": "DescriptiveModelName",
  "primaryPartId": "id_of_root_or_torso_part",
  "instances": [ ...18 to 45 parts... ]
}
Return JSON ONLY. No markdown explanations.`;

    let userPrompt = `User Prompt: "${prompt}"\nIteration: ${iteration}\nConstruct a complete, highly detailed 3D Roblox model matching this exact request with rich part decomposition.`;

    if (iteration > 1 && plan) {
      userPrompt += `\nCritique and Refinement: Add supplementary accent parts, enhance micro-details, improve material contrast, and fix any misalignment from earlier passes.`;
    }

    const result = await this.executeLLMCascade(systemPrompt, userPrompt, 0.35, 4000);

    if (result && Array.isArray(result.instances) && result.instances.length > 0) {
      const sanitized = this.sanitizeModel(result, prompt, iteration);
      return sanitized;
    }

    // Fallback to domain knowledge if cascade was unreachable
    return this.fallback.generateModelIR(plan, prompt, referenceImage, iteration);
  }

  public async generateAnimationIR(
    prompt: string,
    modelIR: RobloxModelIR,
    referenceImage?: string
  ): Promise<RobloxAnimationIR> {
    const systemPrompt = `You are Roblox Asset AI's Master Keyframe Animation Director.
Synthesize a fluid, organic, Disney-quality keyframe animation sequence for Roblox Studio.
Target rig bones: "Torso" (root/waist), "Head" (neck), "LeftArm" (left shoulder), "RightArm" (right shoulder), "LeftLeg" (left hip), "RightLeg" (right hip).

KINETIC PRINCIPLES & DYNAMICS:
1. ANTICIPATION: Subtle reverse coil before forceful movements (e.g. leaning back before a sword slash or wave).
2. SECONDARY MOTION & COUNTER-BALANCE: When arms swing forward, torso rotates slightly; when right leg steps forward, left arm swings forward.
3. ORGANIC SPINAL MOTION: Animate the "Torso" with slight vertical bobbing (position [0, y, 0]) and rotation (pitch/roll/yaw) to make the character look alive, never stiff or robotic!
4. SMOOTH CURVES: Generate 5 to 9 keyframes distributed across the animation length.
5. EASING: Use "Sine", "Quad", or "Cubic" with "InOut" or "Out" for natural deceleration.

OUTPUT JSON SCHEMA:
{
  "assetType": "animation",
  "name": "AnimationName",
  "length": 1.6,
  "loop": true,
  "priority": "Movement" | "Action",
  "fps": 30,
  "keyframes": [
    {
      "time": 0.0,
      "name": "RestPose",
      "poses": [
        { "boneName": "Torso", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "Head", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "LeftArm", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "RightArm", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "LeftLeg", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" },
        { "boneName": "RightLeg", "position": [0,0,0], "rotation": [0,0,0], "easingStyle": "Sine", "easingDirection": "InOut" }
      ]
    }
  ]
}
Return valid JSON only.`;

    const userPrompt = `Generate a Roblox animation sequence for: "${prompt}".`;
    const anim = await this.executeLLMCascade(systemPrompt, userPrompt, 0.3, 2500);

    if (anim && Array.isArray(anim.keyframes) && anim.keyframes.length >= 2) {
      return {
        assetType: 'animation',
        name: anim.name || 'CustomMotion',
        length: typeof anim.length === 'number' ? anim.length : 1.6,
        loop: anim.loop ?? true,
        priority: anim.priority || 'Action',
        fps: anim.fps || 30,
        keyframes: anim.keyframes,
        metadata: {
          prompt,
          generator: this.providerName,
        },
      };
    }

    return this.fallback.generateAnimationIR(prompt, modelIR, referenceImage);
  }

  public async inspectAndCritique(request: VisionInspectionRequest): Promise<IterationCritique> {
    const { prompt, currentModelIR, iterationIndex } = request;

    const systemPrompt = `You are Roblox Asset AI's Senior Vision Critic and Spatial Quality Evaluator.
Evaluate the current Roblox 3D Model candidate against the user's prompt.
Strictly check:
1. Prompt fidelity: Did the model include ALL items, accessories, clothing, and features requested in the prompt?
2. Structural integrity: Are parts grounded at Y=0? Are trims and layers properly offset without coplanar z-fighting?
3. Proportions & balance: Are shapes and scales natural and aesthetically stylized?
4. Material & color harmony: Are contrasting materials (Fabric, Metal, Neon, Wood) utilized effectively?

OUTPUT JSON SCHEMA:
{
  "summary": "Specific, constructive 1-2 sentence evaluation",
  "qualityScore": 0.92,
  "metrics": {
    "proportions": 0.93,
    "geometry": 0.91,
    "materialsAndColors": 0.94,
    "structuralIntegrity": 0.92,
    "promptAdherence": 0.95
  },
  "items": [
    {
      "category": "detail",
      "severity": "minor",
      "description": "Specific flaw or detail improvement",
      "suggestedAction": "ADD_PART",
      "targetPartId": "optional_part_id"
    }
  ]
}
Return JSON only.`;

    const userPrompt = `Prompt: "${prompt}"\nIteration: ${iterationIndex}\nCurrent Model Parts: ${JSON.stringify(
      currentModelIR.instances.map((i: any) => ({ name: i.name, shape: i.shape, size: i.size, pos: i.position, mat: i.material }))
    )}`;

    const critique = await this.executeLLMCascade(systemPrompt, userPrompt, 0.2, 1200);

    if (critique && typeof critique.qualityScore === 'number' && critique.metrics) {
      return {
        summary: critique.summary || 'Vision evaluation completed.',
        qualityScore: Math.min(0.98, Math.max(0.65, critique.qualityScore)),
        metrics: {
          proportions: Number(critique.metrics.proportions) || 0.88,
          geometry: Number(critique.metrics.geometry) || 0.88,
          colorMaterial: Number(critique.metrics.colorMaterial || critique.metrics.materialsAndColors) || 0.9,
          structure: Number(critique.metrics.structure || critique.metrics.structuralIntegrity) || 0.9,
          promptAdherence: Number(critique.metrics.promptAdherence) || 0.92,
          overall: Math.min(0.98, Math.max(0.65, Number(critique.qualityScore) || 0.89)),
        },
        items: Array.isArray(critique.items) ? critique.items : [],
      };
    }

    return this.fallback.inspectAndCritique(request);
  }

  /**
   * Sanitizes, repairs, and enforces constraints on LLM-generated Model IR
   */
  private sanitizeModel(raw: any, prompt: string, iteration: number): RobloxModelIR {
    const validShapes = ['Block', 'Ball', 'Cylinder', 'Wedge'];
    const validMaterials = [
      'SmoothPlastic',
      'Neon',
      'Fabric',
      'Metal',
      'WoodPlanks',
      'Wood',
      'Cobblestone',
      'Glass',
      'Brick',
      'DiamondPlate',
      'Granite',
      'Slate',
      'CorrodedMetal',
    ];

    const instances: RobloxInstanceIR[] = [];
    const usedIds = new Set<string>();

    for (let idx = 0; idx < (raw.instances || []).length; idx++) {
      const p = raw.instances[idx];
      let id = p.id ? String(p.id) : `p_${idx}`;
      while (usedIds.has(id)) {
        id = `${id}_${Math.floor(Math.random() * 100)}`;
      }
      usedIds.add(id);

      const shape = validShapes.includes(p.shape) ? p.shape : 'Block';
      const className = shape === 'Wedge' || p.className === 'WedgePart' ? 'WedgePart' : 'Part';
      const material = validMaterials.includes(p.material) ? p.material : 'SmoothPlastic';

      const size: [number, number, number] = Array.isArray(p.size) && p.size.length >= 3
        ? [Math.max(0.1, Number(p.size[0]) || 1), Math.max(0.1, Number(p.size[1]) || 1), Math.max(0.1, Number(p.size[2]) || 1)]
        : [1, 1, 1];

      const position: [number, number, number] = Array.isArray(p.position) && p.position.length >= 3
        ? [Number(p.position[0]) || 0, Number(p.position[1]) || 0, Number(p.position[2]) || 0]
        : [0, idx * 1.5, 0];

      const rotation: [number, number, number] = Array.isArray(p.rotation) && p.rotation.length >= 3
        ? [Number(p.rotation[0]) || 0, Number(p.rotation[1]) || 0, Number(p.rotation[2]) || 0]
        : [0, 0, 0];

      const color: [number, number, number] = Array.isArray(p.color) && p.color.length >= 3
        ? [
            Math.min(255, Math.max(0, Math.round(Number(p.color[0]) || 120))),
            Math.min(255, Math.max(0, Math.round(Number(p.color[1]) || 120))),
            Math.min(255, Math.max(0, Math.round(Number(p.color[2]) || 120))),
          ]
        : [120, 130, 140];

      const part: RobloxPartIR = {
        id,
        name: p.name ? String(p.name).replace(/[^a-zA-Z0-9_]/g, '') : `Part_${idx}`,
        className,
        shape,
        size,
        position,
        rotation,
        color,
        material: material as any,
        anchored: true,
        canCollide: p.canCollide ?? true,
      };

      instances.push(part);
    }

    const primaryPartId = raw.primaryPartId && usedIds.has(raw.primaryPartId)
      ? raw.primaryPartId
      : instances[0]?.id || 'root_part';

    return {
      assetType: 'model',
      name: raw.name ? String(raw.name).replace(/[^a-zA-Z0-9_]/g, '') : 'GeneratedRobloxAsset',
      primaryPartId,
      instances,
      metadata: {
        prompt,
        iteration,
        generator: this.providerName,
      },
    };
  }

  public async applyCritiqueToModel(
    currentModel: RobloxModelIR,
    critique: IterationCritique,
    prompt: string
  ): Promise<RobloxModelIR> {
    const systemPrompt = `You are Roblox Asset AI's 3D Refiner.
Enhance and modify the given Roblox Model IR based on the visual critique.
Add detailed accent parts, improve alignment, enhance color contrast, or fix flaws mentioned in the critique.
Output valid JSON only matching schema:
{
  "assetType": "model",
  "name": "ModelName",
  "primaryPartId": "id",
  "instances": [ ...updated parts... ]
}`;

    const userPrompt = `User Prompt: "${prompt}"\nCurrent Model IR: ${JSON.stringify(currentModel)}\nCritique Summary: "${critique.summary}"\nCritique Items: ${JSON.stringify(critique.items)}\nProduce the improved Roblox Model IR.`;

    const refined = await this.executeLLMCascade(systemPrompt, userPrompt, 0.35, 3500);
    if (refined && Array.isArray(refined.instances) && refined.instances.length > 0) {
      return this.sanitizeModel(refined, prompt, 2);
    }

    return this.fallback.applyCritiqueToModel(currentModel, critique, prompt);
  }

  public async applyCritiqueToAnimation(
    currentAnimation: RobloxAnimationIR,
    critique: IterationCritique,
    prompt: string
  ): Promise<RobloxAnimationIR> {
    return this.fallback.applyCritiqueToAnimation(currentAnimation, critique, prompt);
  }
}
